import numpy as np
import sys
import os
import cPickle

from GenPropertyFeaturesFromHHM import LoadTestData4Properties

## this script generates input features for multiple proteins from HHM files for property prediction

def Usage():
	print 'python GenPropertyFeaturesForMultiProteins.py proteinList hhmFolder [savefile]'
	print '	This script generates a property feature file (in PKL) for multiple proteins from hhm files in a folder'
	print '	proteinList: a file containing a list of protein names, each in one line'
	print '	hhmFolder: containing hhm files generated by hhmake from a3m file'
	print '	if not specified, the result file is named after proteinListFileName.propertyFeatures.pkl'

def main(argv):

	if len(argv) < 2:
		Usage()
		exit(1)

	proteinNameFile = argv[0]
	hhmFolder = argv[1]
	if not os.path.isdir(hhmFolder):
		print 'ERROR: the specified folder for .hhm files does not exist: ', hhmFolder
		exit(1)

	savefile = os.path.basename(proteinNameFile) + '.propertyFeatures.pkl'
	if len(argv) > 2:
		savefile = argv[2]

	with open(proteinNameFile, 'r') as fh:
		proteins = [ line.strip() for line in list(fh) ]

	features = []
	for protein in proteins:
		hhmFile = os.path.join(hhmFolder, protein + '.hhm')
		if not os.path.isfile(hhmFile):
			print 'ERROR: hhmFile does not exist: ', hhmFile
			continue
		
		feature = LoadTestData4Properties(hhmFile, protein)
		if feature is None:
			print 'ERROR: failed to load hhm file: ', hhmFile
			continue
		features.append(feature)

	with open(savefile, 'wb') as fh:
		cPickle.dump(features, fh, protocol=cPickle.HIGHEST_PROTOCOL)

if __name__ == "__main__":
        main(sys.argv[1:])

