import numpy as np
import sys
import os
import cPickle

sys.path.append('../')
import PropertyUtils
from LoadAngleFile import LoadAngleFile

sys.path.append(os.path.join(os.environ['ModelingHome'], 'Common') )
from LoadTPLTGT import load_tpl as LoadTPL
from LoadTPLTGT import load_tgt as LoadTGT

## this script generates input features and labels for property prediction from TGT files and Yujuan's angle files

def Usage():
	print 'python GenPropertyFeaturesFromTPL.py tgt_file angle_file'
	print '	tgt_file: the tgt file generated for template-based modeling'
	print '	angle_file: the angle file generated by Yujuan'


def LoadTrainData4Properties(tgtFile, angFile):

	tgt = LoadTGT(tgtFile)
	Ang = LoadAngleFile(angFile)

	assert tgt['sequence'] == Ang['sequence']
	#assert ( tSS == aSS for tSS, aSS, m in zip(tpl['SS_str'], Ang['SS'], tpl['missing']) if m!=1 )
	##assert tpl['SS_str'] == Ang['SS']

	## merge tpl and ang to generate a new training and validation file

	protein = dict()
	
	protein['name'] = tgt['name']
	protein['sequence'] = tgt['sequence']
	protein['length'] = tgt['length']
	protein['NEFF'] = tgt['NEFF']

	protein['PSFM'] = tgt['PSFM']
	protein['PSSM'] = tgt['PSSM']

	protein['predSS3'] = tgt['SS3']
	protein['predSS8'] = tgt['SS8']
	protein['predACC'] = tgt['ACC_prob']

	protein['SS'] = Ang['SS']
	protein['DISO'] = Ang['DISO']
	protein['CLE'] = Ang['CLE']
	protein['Phi'] = Ang['Phi']
	protein['Psi'] = Ang['Psi']
	protein['Theta'] = Ang['Theta']
	protein['Tau'] = Ang['Tau']
	protein['Omg'] = Ang['Omg']

	##merge Phi and Psi
	protein['PhiPsi'] = np.transpose( np.array([ protein['Phi'], protein['Psi'] ]) )

	##merge Theta and Tau
	protein['ThetaTau'] = np.transpose( np.array([ protein['Theta'], protein['Tau'] ]) )

	## the missing residues have no 3D coordinates and thus, angles and solvent accessibility
	protein['Missing'] = Ang['Missing']

	protein['SS8'] = protein['SS']

	protein['SS3'] = ''.join([PropertyUtils.SS8Letter2SS3Letter[c] for c in protein['SS8'] ] )

	protein['ForTrain'] = True


	return protein

def main(argv):

	if len(argv) < 2:
		Usage()
		exit(-1)

	tgtFile = argv[0]
	angFile = argv[1]

	protein = LoadTrainData4Properties(tgtFile, angFile)

	savefile = protein['name'] + '.propertyFeatures.pkl'
	fh = open(savefile, 'wb')
	cPickle.dump( protein, fh, protocol=cPickle.HIGHEST_PROTOCOL)
	fh.close()

if __name__ == "__main__":
        main(sys.argv[1:])

