import os
import sys
import cPickle
import numpy as np

from DL4DistancePrediction4 import ContactUtils

## this script adds contact number of Ca and Cb atoms to a tpl.pkl file
def Usage():
	print 'python AddThetaTau2TPLPKL.py tplFile_PKL [savefile]'
	print '	tplFile_PKL: the template file in PKL format with suffix .tpl.pkl, generated by HHM2TPL.py'
	print '	savefile: the file for result saving (optional). If not specified, save to a file in current work directoy, but with the same name as the input file'

if len(sys.argv) < 2:
	Usage()
	exit(1)

tplFile = sys.argv[1]

savefile = os.path.basename(tplFile)
if len(sys.argv) >= 3:
	savefile = sys.argv[2]

if not os.path.isfile(tplFile):
	print 'ERROR: the tpl file does not exist: ', tplFile
	exit(1)

with open(tplFile, 'rb') as fh:
	tpl = cPickle.load(fh)

oriMatrix = tpl['atomOrientationMatrix']
seqLen = tpl['length']

Theta = np.array([ -720 ] * seqLen, dtype=np.float16)
for i in range(seqLen-2):
	Theta[i+1] = oriMatrix['Ca1Ca2Ca3'][i, i+2]

Tau = np.array([ -720 ] *seqLen, dtype=np.float16)
for i in range(seqLen-2):
	Tau[i+2]=oriMatrix['Ca1Ca2Ca3Ca4'][i, i+2]

"""
## for debug
for i, theta, tau in zip(range(seqLen), Theta, Tau):
	print i, theta, tau
"""

tpl['Theta'] = Theta
tpl['Tau' ] = Tau

## save
with open(savefile, 'w') as fh:
	cPickle.dump(tpl, fh, protocol=cPickle.HIGHEST_PROTOCOL)
