import os
import sys
import numpy as np
import cPickle
import scipy
from scipy import spatial
from LoadTPLTGT import load_tgt as LoadTGT

InvalidDistance = -1

def Usage():
	print ' python TGT2PKL.py tgtfile [ResDir]'
	print '	This script generates a simple .tgt.pkl file from an old .tgt file'
	print '	the the .tgt file is generated by an old TGT_package '
	print '	the resultant file is named after proteinName.tgt.pkl and saved to ResDir if provided or current work directory'

if __name__ == "__main__":
	if len(sys.argv) < 2:
		Usage()
		exit(1)

	tgtfile = sys.argv[1]

	ResDir=os.getcwd()
	if len(sys.argv)>=3:
		ResDir = sys.argv[2]
		if not os.path.isdir(ResDir):
			print 'ERROR: the folder for result saving does not exist: ', ResDir
			exit(1)

	tgt = LoadTGT(tgtfile)

	savefile = os.path.join(ResDir, tgt['name'] + '.tgt.pkl')
	with open(savefile, 'w') as fh:
		cPickle.dump(tgt, fh, protocol=cPickle.HIGHEST_PROTOCOL)
