#!/bin/bash

GPU=-1

if [ $# -lt 2 ]; then
	echo $0 "targetName RootDir [gpu]"
	echo "  RootDir (e.g. 1pazA_OUT/) shall contain a subfolder target_contact, which in turn shall contain feature subfolders generated by GenA3M.sh and GenDistanceFeaturesFromA3M.sh"
	echo "  RootDir shall also contain a sequence file named after target.seq in FASTA format"
	echo "  result is saved back to RootDir/ "
	echo "  gpu can be -1 (default), cuda0, cuda1, cuda2, and cuda3. if set to -1, will automatically select a GPU"
	exit 1
fi

if [ $# -ge 3 ]; then
	GPU=$3
fi

if [ $GPU != "-1" ]; then
	GPU=`echo -n $GPU | tail -c 1 `
fi

if [[ -z "${DL4DistancePredHome}" ]]; then
	echo "Please set the environmental variable DL4DistancePredHome, e.g., $HOME/3DModeling/DL4DistancePrediction2"
	exit 1
fi

proteinName=$1
rootDir=$2

if [ ! -d $rootDir ]; then
	echo "the input folder for feature files does not exist: " $rootDir
	exit 1
fi

seqFile=$rootDir/${proteinName}.seq

if [ ! -f $seqFile ]; then
	echo "the sequence file does not exist: " $seqFile
	exit 1
fi

inputFeature=$rootDir/DistancePred/${proteinName}.distanceFeatures.pkl
if [ ! -f $inputFeature ]; then
	$DL4DistancePredHome/Scripts/CollectDistanceFeatures.sh $proteinName $rootDir
	if [ $? -ne 0 ]; then
                echo "Failed to collect input feature for distance prediction!"
                exit 1
        fi

fi

if [ ! -f $inputFeature ]; then
	echo "Cannot find the input feature file: " $inputFeature
	exit 1
fi

UseRemoteMachine=false
localMachine=`hostname | cut -f1 -d'.' `
if [ $localMachine == "raptorx" -o $localMachine == "raptorx2" -o $localMachine == "raptorx3" -o $localMachine == "cruncher" ]; then
        UseRemoteMachine=true
elif [[ $localMachine == compute* ]]; then
        UseRemoteMachine=true
fi

if $UseRemoteMachine; then
	accounts=("RaptorX@raptorx4.uchicago.edu" "RaptorX@raptorx5.uchicago.edu" "RaptorX@raptorx6.uchicago.edu" "RaptorX@raptorx7.uchicago.edu")
	remoteAccount=${accounts[$RANDOM % ${#accounts[@]} ]}
        #remoteAccount="RaptorX@raptorx5.uchicago.edu"
        $DL4DistancePredHome/Scripts/PredictDistanceByRemote.sh $seqFile $inputFeature $remoteAccount
else
        $DL4DistancePredHome/Scripts/PredictDistance4PKLInput.sh $seqFile $inputFeature

fi

