#!/bin/sh

if [ $# -lt 5 ]; then
	echo $0 SeqFile FragDir PredictedDistMatrix PredictedProperty FlagTemplateFile [savefolder [numModels] ]
	echo "this script generates constrains from predicted inter-residue relationship and Phi/Psi angles and then use fragment assembly to fold a protein"
	echo "	SeqFile: the sequence file in FASTA format"
	echo "	FragDir: the folder for fragment library of the protein to be folded, generated by tools in fragments_make/"
	echo "	PredictedDistMatrix: a PKL file (ending with predictedDistMatrix.pkl) for predicted distance/orientation information"
	echo " 	PredictedProperty: a PKL file (ending with predictedProperties.pkl) for predicted Phi/Psi information"
	echo "		if this entry is a special string cst, then PredictedDistMatrix is interpreted as a Rosetta constraint file instead of a PKL file"
	echo "	FlagTemplateFile: a template text file for flags used by Rosetta"
	echo "	numModels: the number of decoys to be generated, default 1"
	echo "	savefolder: the folder for decoys to be generated"
	exit 1
fi

if [[ -z "${DistanceFoldingHome}" ]]; then
        echo "ERROR: Please set the environmental variable DistanceFoldingHome, e.g., $HOME/3DModeling/Folding"
        exit 1
fi

if [[ -z "${ROSETTA}" ]]; then
        #echo "ERROR: Please set the environmental variable ROSETTA, e.g., /mnt/data/RaptorXCommon/Rosetta_Package/rosetta_bin_linux_2018.48.60516_bundle/"
	ROSETTA=/mnt/data/RaptorXCommon/Rosetta_Package/rosetta_bin_linux_2020.03.61102_bundle
        exit 1
fi

if [ ! -d $ROSETTA ]; then
        echo "ERROR: Please set the environmental variable ROSETTA, e.g., /mnt/data/RaptorXCommon/Rosetta_Package/rosetta_bin_linux_2018.48.60516_bundle/"
	exit 1
fi

RosettaBin=$ROSETTA/main/source/bin/
RosettaDB=$ROSETTA/main/database/
FragFoldProgram=$RosettaBin/AbinitioRelax.static.linuxgccrelease

SeqFile=`readlink -f $1`
target=`basename $SeqFile `
target=`echo $target | cut -f1 -d'.'`

FragDir=`readlink -f $2`
pairMatrixFile=$3
propertyFile=$4
FlagTemplateFile=`readlink -f $5`

savefolder=`pwd`
if [ $# -ge 6 ]; then
	savefolder=$6
fi

numModels=1
if [ $# -ge 7 ]; then
	numModels=$7
fi

if [ ! -f $pairMatrixFile ]; then
        echo "ERROR: the file for predicted distance/orientation info does not exist: $pairMatrixFile"
        exit 1
fi

processID=$$

FilePrefix=${target}.${processID}
OutDirPrefix=$FilePrefix
SilentFilePrefix=$FilePrefix
ScoreFilePrefix=$FilePrefix

## add processID to avoid overwriting
OutDir=$savefolder/${target}-FoldResults.${processID}
mkdir -p $OutDir

cmd=`readlink -f $0`
cmdDir=`dirname $cmd`

date

if [ "$propertyFile" == "cst" ]; then
	## treat pairMatrixFile as a constraint file instead of a PKL file 
	cstfile=$pairMatrixFile
else
	if [ ! -f $propertyFile ]; then
                echo "ERROR: the file for predicted property info does not exist: $propertyFile"
                exit 1
        fi

	## create a temporary cstfolder
	cstfolder=$(mktemp -d -t tmpCstDir4${target}-XXXXXXXXXX)
	cstfolder=`readlink -f $cstfolder`
	$DistanceFoldingHome/Scripts4Rosetta/GenRosettaPotential.sh $pairMatrixFile $propertyFile $cstfolder
	cstfile=$cstfolder/$target.pairPotential4Rosetta.SPLINE.txt
fi

##generate a flag file for Rosetta options
flagFile=${target}.${processID}.flags.txt
cp $FlagTemplateFile $flagFile

sed -i "s@SeqFile@${SeqFile}@" $flagFile
sed -i "s@TARGET@${target}@" $flagFile
sed -i "s@FragDir@${FragDir}@" $flagFile
sed -i "s@CstFile@${cstfile}@" $flagFile
sed -i "s@RosettaDB@${RosettaDB}@" $flagFile
sed -i "s@NumModels@${numModels}@" $flagFile
sed -i "s@OutDir@${OutDir}@" $flagFile

SilentFile=$SilentFilePrefix.silent.out
ScoreFile=$ScoreFilePrefix.score.txt

sed -i "s@SilentFile@${SilentFile}@" $flagFile 
sed -i "s@ScoreFile@${ScoreFile}@" $flagFile

## execute the folding program
$FragFoldProgram @$flagFile

FinalResDir=$savefolder/${target}-FoldResults
mkdir -p $FinalResDir

for resfile in $OutDir/*pdb
do
	bname=`basename $resfile .pdb `
	bname=`echo $bname | cut -c6- `
	mv $resfile $FinalResDir/${target}.${processID}M$bname.pdb
done
rm -rf $OutDir

if [ "$propertyFile" != "cst" ]; then
	rm -rf $cstfolder
fi

date
